<?php

/**
 * Implementation of hook_theme
 */
function fb_social_share_theme(){
  return array(
    'fb_social_share_widget' => array(
      'arguments' => array('url' => NULL) 
      ) 
  );
}

/**
 * Implementation of hook_block
 */
function fb_social_share_block($op = 'list', $delta = 0){
  
  if ($op == "list") {
    $block = array();
    $block[0]["info"] = t('fb share');
    return $block;
  }
  else if ($op == 'view') {
    $url = fb_social_url($_GET['q']);
    $layout = variable_get('fb_social_share_layout_style', 'button_count');
    
    $block_content .= theme('fb_social_share_widget', $url);
    $block['subject'] = 'Facebook Share';
    $block['content'] = $block_content;
    return $block;
  }
}

/**
 * Implementation of hook_menu
 */
function fb_social_share_menu(){
  
  $items = array();
  
  $items['admin/settings/fb/social/share'] = array(
      'title' => 'share', 
      'description' => 'Facebook share module settings', 
      'page callback' => 'drupal_get_form', 
      'page arguments' => array(
          'fb_social_share_settings_form' 
      ), 
      'access callback' => 'user_access', 
      'access arguments' => array(
          'access administration pages' 
      ), 
      'file' => 'fb_social_share.admin.inc', 
      'type' => MENU_LOCAL_TASK 
  );
  
  return $items;
}

/**
 * theme callback function
 */
function theme_fb_social_share_widget($url){
  
  $layout = variable_get('fb_social_share_layout_style', 'button_count');
  return '<fb:share-button href="' . $url . '" type ="' . $layout . '" ></fb:share-button>';

}

/**
 * Implementation of hook_link
 */
function fb_social_share_link($type, $object, $teaser = FALSE){
  
  if ('node' != $type) {
    return;
  }
  elseif ($teaser && ! variable_get('fb_social_share_check_teasers', 1)) {
    return;
  }
  $links = array();
  if ($type == 'node' && fb_social_share_type($object->type)) {
    $links['fb_social_share_class'] = array(
        'title' => theme('fb_social_share_widget', fb_social_url('node/' . $object->nid)), 
        'html' => TRUE 
    );
  }
  
  return $links;
}

function fb_social_share_type($type){
  $fb_share_types = variable_get('fb_social_share_node_types', array());
  return (isset($fb_share_types[$type]) && $fb_share_types[$type]) ? TRUE : FALSE;
}